sudo: required
dist: bionic
language: bash
python:
  - "3.6"
services: docker
before_install:
  - echo "We are in Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
      docker tag my-spring-boot:latest ${DOCKER_USERNAME}/my-spring-boot:$TRAVIS_JOB_ID;
      docker push ${DOCKER_USERNAME}/my-spring-boot:$TRAVIS_JOB_ID;
  on:
      branch: master
after_success: 
  - sudo apt-get -y install python3-pip python-dev
  - sudo pip3 install -U setuptools
  - sudo pip3 install -U virtualenvwrapper
  - python3 -V
  - pip3 -V
  - pip3 uninstall wheel
  - pip3 install wheel
  - pip3 install awscli --upgrade --user
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  - docker tag my-spring-boot:latest $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - docker push $IMAGE_REPO_URL:$TRAVIS_JOB_ID
  - add-apt-repository ppa:eugenesan/ppa
  - sudo apt-get update
  - sudo apt-get install jq -y
  - curl https://raw.githubusercontent.com/silinternational/ecs-deploy/master/ecs-deploy | sudo tee -a /usr/bin/ecs-deploy
  - sudo chmod +x /usr/bin/ecs-deploy
  - echo "AWS ECS-DEPLOY Setup is Configured"
  - ecs-deploy -c $CLUSTER_NAME -n $SERVICE_NAME -i $IMAGE_REPO_URL:$TRAVIS_JOB_ID -r $AWS_DEFAULT_REGION --skip-deployments-check
notifications:
  email: false    
