language: bash
services: docker
before_install:
  - echo "We are in Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
      docker tag my-spring-boot ${DOCKER_USERNAME}/my-spring-boot;
      docker push ${DOCKER_USERNAME}/my-spring-boot;
  on:
      branch: master
notifications:
  email: false    
