version: "3.7"

services:
  my-spring-boot:
    image: my-spring-boot
    container_name: my-spring-boot
    build: .
    environment:
      spring_profiles_active: docker
    ports:
      - 3000:3000
    depends_on:
      - some-postgres
    networks:
      - sb_net
    command: ["./wait-for-it.sh","-t", "10", "some-postgres:5432", "--strict","--", "mvn", "spring-boot:run"]

  
  some-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150158
      POSTGRES_DB: spring_boot
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - sb_net 
    volumes:
      - ./output_data:/var/lib/postgresql/data/pgdata
    

networks:
   sb_net:
      name: sb_net