version: "3.7"

services:
  my-spring-boot:
    image: my-spring-boot
    build: .
    environment:
      spring_profiles_active: docker
    ports:
      - 3000:3000
    depends_on:
      - some-postgres
    networks:
      - sb_net
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 4
  
  some-postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 150158
      POSTGRES_DB: spring_boot
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - sb_net 
    volumes:
      - ./output_data:/var/lib/postgresql/data/pgdata
    

networks:
   sb_net:
      name: sb_net