insert into client (address, birth, last_name, name, enabled) values ('37 Bunting Hill', '2021-12-15', 'Renbold', 'Séréna', false);
insert into client (address, birth, last_name, name, enabled) values ('65945 Riverside Point', '2021-04-08', 'Bradley', 'Réservés', false);
insert into client (address, birth, last_name, name, enabled) values ('14488 Manley Street', '2021-05-14', 'Britian', 'Anaël', false);
insert into client (address, birth, last_name, name, enabled) values ('5598 Chinook Alley', '2021-02-01', 'Demanche', 'Angèle', true);
insert into client (address, birth, last_name, name, enabled) values ('01627 Carey Avenue', '2021-06-23', 'Toulamain', 'Maëlle', true);
insert into client (address, birth, last_name, name, enabled) values ('51 Gerald Court', '2021-05-19', 'Grassick', 'Mahélie', false);
insert into client (address, birth, last_name, name, enabled) values ('7917 Village Green Road', '2021-09-16', 'O''Mara', 'Eléonore', true);
insert into client (address, birth, last_name, name, enabled) values ('14 Roth Lane', '2021-08-29', 'Livoir', 'Stévina', true);
insert into client (address, birth, last_name, name, enabled) values ('08180 Anzinger Center', '2021-04-20', 'Ketcher', 'Vénus', false);
insert into client (address, birth, last_name, name, enabled) values ('4 Briar Crest Pass', '2021-09-27', 'Jendrys', 'Clémence', true);
insert into client (address, birth, last_name, name, enabled) values ('87841 Westridge Way', '2021-08-04', 'Lathwood', 'Mahélie', false);
insert into client (address, birth, last_name, name, enabled) values ('5740 Eagle Crest Point', '2021-02-01', 'De Wolfe', 'Laurélie', false);
insert into client (address, birth, last_name, name, enabled) values ('6149 Rusk Alley', '2021-03-01', 'Scad', 'Laurène', true);
insert into client (address, birth, last_name, name, enabled) values ('5 Oak Lane', '2021-12-08', 'Cabell', 'Aloïs', false);
insert into client (address, birth, last_name, name, enabled) values ('24812 New Castle Road', '2021-11-13', 'Kearns', 'Mélodie', true);
insert into client (address, birth, last_name, name, enabled) values ('1 Coolidge Junction', '2021-05-23', 'Ruddy', 'Aí', false);
insert into client (address, birth, last_name, name, enabled) values ('2 Shoshone Road', '2021-12-10', 'Colborn', 'Léone', false);
insert into client (address, birth, last_name, name, enabled) values ('58 Lotheville Way', '2021-04-18', 'Faloon', 'Naéva', false);
insert into client (address, birth, last_name, name, enabled) values ('229 Upham Center', '2021-09-03', 'Mathias', 'Stévina', false);
insert into client (address, birth, last_name, name, enabled) values ('50328 Troy Place', '2021-01-17', 'Maltby', 'Eugénie', true);
insert into client (address, birth, last_name, name, enabled) values ('44 Tennyson Lane', '2021-03-24', 'Knewstubb', 'Björn', false);
insert into client (address, birth, last_name, name, enabled) values ('5022 Karstens Way', '2021-11-02', 'Fraser', 'Bécassine', false);
insert into client (address, birth, last_name, name, enabled) values ('69741 Packers Avenue', '2021-03-25', 'Matej', 'Ophélie', true);
insert into client (address, birth, last_name, name, enabled) values ('65 Ramsey Way', '2021-02-14', 'Gregorin', 'Björn', true);
insert into client (address, birth, last_name, name, enabled) values ('50 Old Gate Trail', '2021-02-11', 'Winsom', 'Andrée', false);
insert into client (address, birth, last_name, name, enabled) values ('83 La Follette Trail', '2021-02-27', 'Meake', 'Salomé', false);
insert into client (address, birth, last_name, name, enabled) values ('41479 High Crossing Hill', '2021-06-30', 'Heggs', 'Ruì', false);
insert into client (address, birth, last_name, name, enabled) values ('40 Rockefeller Lane', '2021-03-13', 'Lockhart', 'Laurélie', false);
insert into client (address, birth, last_name, name, enabled) values ('5 Kensington Road', '2021-08-09', 'Lory', 'Daphnée', false);
insert into client (address, birth, last_name, name, enabled) values ('23 Oakridge Hill', '2021-07-03', 'Edards', 'Nuó', false);
insert into client (address, birth, last_name, name, enabled) values ('1 La Follette Circle', '2021-09-16', 'Eckersall', 'Renée', false);
insert into client (address, birth, last_name, name, enabled) values ('54847 Mcbride Place', '2021-08-31', 'Oneile', 'Célia', false);
insert into client (address, birth, last_name, name, enabled) values ('87 Becker Point', '2021-11-29', 'Bonham', 'Gösta', false);
insert into client (address, birth, last_name, name, enabled) values ('80240 Banding Junction', '2021-01-26', 'Kupka', 'Gösta', false);
insert into client (address, birth, last_name, name, enabled) values ('71573 Glendale Street', '2021-03-18', 'Bog', 'Lèi', false);
insert into client (address, birth, last_name, name, enabled) values ('44 Farwell Pass', '2021-09-18', 'Newton', 'Kévina', true);
insert into client (address, birth, last_name, name, enabled) values ('69 Nova Pass', '2021-05-26', 'Britian', 'Réjane', false);
insert into client (address, birth, last_name, name, enabled) values ('45499 Truax Road', '2022-01-01', 'Morales', 'Océane', false);
insert into client (address, birth, last_name, name, enabled) values ('3812 Gerald Crossing', '2021-10-05', 'Eim', 'Séréna', true);
insert into client (address, birth, last_name, name, enabled) values ('1 Porter Pass', '2021-10-26', 'Storie', 'Méline', true);
insert into client (address, birth, last_name, name, enabled) values ('8983 Chinook Street', '2021-05-23', 'Cordet', 'Yáo', false);
insert into client (address, birth, last_name, name, enabled) values ('6331 Pleasure Alley', '2021-09-08', 'Plaxton', 'Lucrèce', true);
insert into client (address, birth, last_name, name, enabled) values ('9 Mesta Plaza', '2021-06-21', 'Ronchetti', 'Lèi', false);
insert into client (address, birth, last_name, name, enabled) values ('55 Lakeland Center', '2021-06-13', 'Eivers', 'Åslög', false);
insert into client (address, birth, last_name, name, enabled) values ('47 Eliot Hill', '2021-09-24', 'Leach', 'Crééz', true);
insert into client (address, birth, last_name, name, enabled) values ('91 Heffernan Alley', '2021-04-17', 'Rapin', 'Aí', true);
insert into client (address, birth, last_name, name, enabled) values ('80259 Merchant Court', '2021-09-30', 'Scawton', 'Lài', true);
insert into client (address, birth, last_name, name, enabled) values ('83321 Hovde Court', '2021-06-13', 'Baston', 'Pål', false);
insert into client (address, birth, last_name, name, enabled) values ('20 Superior Terrace', '2021-08-13', 'Hessle', 'Estève', false);
insert into client (address, birth, last_name, name, enabled) values ('2552 Londonderry Terrace', '2021-04-03', 'Punshon', 'Håkan', true);
insert into client (address, birth, last_name, name, enabled) values ('2 Transport Terrace', '2021-12-29', 'Housen', 'Gwenaëlle', false);
insert into client (address, birth, last_name, name, enabled) values ('8880 School Alley', '2021-05-27', 'Caitlin', 'Yóu', false);
insert into client (address, birth, last_name, name, enabled) values ('00 Pennsylvania Circle', '2021-04-23', 'Rennels', 'Yáo', false);
insert into client (address, birth, last_name, name, enabled) values ('806 Kedzie Drive', '2021-02-01', 'Vignaux', 'Håkan', true);
insert into client (address, birth, last_name, name, enabled) values ('72129 Old Gate Terrace', '2021-10-29', 'Dat', 'Eléonore', false);
insert into client (address, birth, last_name, name, enabled) values ('7711 Kipling Court', '2021-09-30', 'Mabon', 'Kévina', false);
insert into client (address, birth, last_name, name, enabled) values ('7 Bartelt Crossing', '2021-04-20', 'Breckin', 'Östen', true);
insert into client (address, birth, last_name, name, enabled) values ('8148 Merry Alley', '2021-11-29', 'Screas', 'Maëlys', false);
insert into client (address, birth, last_name, name, enabled) values ('6 Springs Terrace', '2021-12-29', 'Adcocks', 'Rachèle', false);
insert into client (address, birth, last_name, name, enabled) values ('57615 Bartelt Hill', '2021-09-28', 'Baradel', 'Agnès', false);
insert into client (address, birth, last_name, name, enabled) values ('4 Spaight Trail', '2021-03-31', 'Airlie', 'Renée', false);
insert into client (address, birth, last_name, name, enabled) values ('01816 Sullivan Lane', '2021-10-27', 'Tilling', 'Annotés', true);
insert into client (address, birth, last_name, name, enabled) values ('313 Toban Road', '2021-10-24', 'Sallarie', 'Marlène', true);
insert into client (address, birth, last_name, name, enabled) values ('59 Clove Parkway', '2021-08-13', 'Southwell', 'Félicie', false);
insert into client (address, birth, last_name, name, enabled) values ('03 Tennessee Road', '2021-04-21', 'Seiller', 'Bérengère', false);
insert into client (address, birth, last_name, name, enabled) values ('98885 Bartillon Park', '2021-06-04', 'Priddie', 'Méthode', true);
insert into client (address, birth, last_name, name, enabled) values ('68667 Portage Way', '2021-05-17', 'Spridgen', 'Marie-françoise', true);
insert into client (address, birth, last_name, name, enabled) values ('34 Atwood Center', '2021-02-19', 'Glasper', 'Fèi', false);
insert into client (address, birth, last_name, name, enabled) values ('73717 Golf View Circle', '2021-02-24', 'Becraft', 'Ruò', false);
insert into client (address, birth, last_name, name, enabled) values ('5053 Service Lane', '2021-12-22', 'Queen', 'Marlène', false);
insert into client (address, birth, last_name, name, enabled) values ('13165 Transport Drive', '2021-11-17', 'Ashard', 'Régine', true);
insert into client (address, birth, last_name, name, enabled) values ('386 Grayhawk Parkway', '2021-07-07', 'Knowller', 'Yóu', false);
insert into client (address, birth, last_name, name, enabled) values ('7082 Sunfield Circle', '2021-09-21', 'Beecraft', 'Åke', false);
insert into client (address, birth, last_name, name, enabled) values ('73943 Cody Center', '2021-08-05', 'Morffew', 'Clémentine', false);
insert into client (address, birth, last_name, name, enabled) values ('77773 Bay Point', '2021-03-20', 'Simoncello', 'Cinéma', false);
insert into client (address, birth, last_name, name, enabled) values ('33582 Talisman Street', '2021-09-17', 'Heasman', 'Vénus', true);
insert into client (address, birth, last_name, name, enabled) values ('99201 Dwight Parkway', '2021-05-31', 'Fearnyhough', 'Méthode', false);
insert into client (address, birth, last_name, name, enabled) values ('3571 Ridgeview Parkway', '2021-02-21', 'Ogelbe', 'Pål', false);
insert into client (address, birth, last_name, name, enabled) values ('6013 Schiller Court', '2021-06-09', 'July', 'Solène', false);
insert into client (address, birth, last_name, name, enabled) values ('6142 Twin Pines Avenue', '2021-01-14', 'Bonnor', 'Frédérique', false);
insert into client (address, birth, last_name, name, enabled) values ('99 North Parkway', '2021-05-31', 'Hallet', 'Josée', false);
insert into client (address, birth, last_name, name, enabled) values ('048 Kropf Lane', '2021-09-01', 'Stichel', 'Mårten', false);
insert into client (address, birth, last_name, name, enabled) values ('1410 Golf Hill', '2021-03-19', 'Sparks', 'Méryl', false);
insert into client (address, birth, last_name, name, enabled) values ('44357 Springs Trail', '2021-03-08', 'Fawks', 'Françoise', true);
insert into client (address, birth, last_name, name, enabled) values ('99068 Straubel Way', '2021-06-15', 'Icke', 'Esbjörn', true);
insert into client (address, birth, last_name, name, enabled) values ('2585 Kenwood Road', '2021-05-02', 'Walisiak', 'Marylène', true);
insert into client (address, birth, last_name, name, enabled) values ('0121 Ronald Regan Trail', '2021-06-15', 'Brennen', 'Annotée', true);
insert into client (address, birth, last_name, name, enabled) values ('11656 Harper Pass', '2021-03-31', 'Gorch', 'Publicité', true);
insert into client (address, birth, last_name, name, enabled) values ('259 Fulton Trail', '2021-11-22', 'Goldthorp', 'Mélys', false);
insert into client (address, birth, last_name, name, enabled) values ('2 Warbler Park', '2021-08-18', 'Thorius', 'Nadège', true);
insert into client (address, birth, last_name, name, enabled) values ('46176 Shasta Lane', '2021-01-23', 'Ulyet', 'Danièle', false);
insert into client (address, birth, last_name, name, enabled) values ('29058 Shelley Drive', '2022-01-08', 'Adami', 'Estée', true);
insert into client (address, birth, last_name, name, enabled) values ('77209 David Way', '2021-12-08', 'Johns', 'Mélissandre', false);
insert into client (address, birth, last_name, name, enabled) values ('17 Havey Court', '2021-10-14', 'MacGillavery', 'Gaïa', false);
insert into client (address, birth, last_name, name, enabled) values ('908 Mcbride Plaza', '2021-07-17', 'Niesegen', 'Mélia', true);
insert into client (address, birth, last_name, name, enabled) values ('906 David Point', '2021-08-03', 'Credland', 'Félicie', true);
insert into client (address, birth, last_name, name, enabled) values ('15099 Dryden Place', '2021-11-14', 'Oliphand', 'Léane', true);
insert into client (address, birth, last_name, name, enabled) values ('15 Charing Cross Center', '2021-12-29', 'Costan', 'Cunégonde', false);
insert into client (address, birth, last_name, name, enabled) values ('797 Graceland Lane', '2021-08-28', 'Dillicate', 'Noëlla', false);
insert into client (address, birth, last_name, name, enabled) values ('34257 Kings Terrace', '2021-01-14', 'Gouldstraw', 'Björn', false);
